Envios/config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :envios
  root 'envios#index'

  

end

Envios/app/models/envio.rb
class Envio < ActiveRecord::Base
end

Envios/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

Envios/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

Envios/app/controllers/envios_controller.rb
class EnviosController < ApplicationController
  before_action :set_envio, only: [:show, :edit, :update, :destroy]

  # GET /envios
  # GET /envios.json
  def index
    @envios = Envio.all
  end

  # GET /envios/1
  # GET /envios/1.json
  def show
  end

  # GET /envios/new
  def new
    @envio = Envio.new
  end

  # GET /envios/1/edit
  def edit
  end

  # POST /envios
  # POST /envios.json
  def create
    @envio = Envio.new(envio_params)

    respond_to do |format|
      if @envio.save
        format.html { redirect_to @envio, notice: 'Envio was successfully created.' }
        format.json { render :show, status: :created, location: @envio }
      else
        format.html { render :new }
        format.json { render json: @envio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /envios/1
  # PATCH/PUT /envios/1.json
  def update
    respond_to do |format|
      if @envio.update(envio_params)
        format.html { redirect_to @envio, notice: 'Envio was successfully updated.' }
        format.json { render :show, status: :ok, location: @envio }
      else
        format.html { render :edit }
        format.json { render json: @envio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /envios/1
  # DELETE /envios/1.json
  def destroy
    @envio.destroy
    respond_to do |format|
      format.html { redirect_to envios_url, notice: 'Envio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_envio
      @envio = Envio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def envio_params
      params[:envio].permit(:status,:reference,:origin,:destiny,:department,:comments,:date,:idUser,:idTransport,:idDetail)
      
    end
end

Envios/app/helpers/application_helper.rb
module ApplicationHelper
end

Envios/app/helpers/envios_helper.rb
module EnviosHelper
end

Envios/app/views/envios/_form.html.erb
<%= form_for(@envio) do |f| %>
  <% if @envio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@envio.errors.count, "error") %> prohibited this envio from being saved:</h2>

      <ul>
      <% @envio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class ="field">
  	<%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class ="field">
  <%= f.label :reference%>
  <%= f.text_field :reference%>
  </div>
  <div class ="field">
  <%= f.label :origin%>
  <%= f.text_field :origin%>
  </div> 
  <div class ="field">
  <%= f.label :destiny %>
  <%= f.text_field :destiny %>	
  </div> 
  <div class ="field">
  <%= f.label :department%>
  <%= f.text_field :department%>
  </div> 
  <div class ="field">
  <%= f.label :comments%>
  <%= f.text_field :comments%>
  </div> 	
  <div class ="field">
  <%= f.label :date%>
  <%= f.text_field :date%>
  	</div>
  <div class = "field">
  	<%= f.label :idUser%>
  	<%= f.text_field :idUser%>
  	
  	</div>
  <div class = "field">
  	<%= f.label :idTransport%>
  	<%= f.text_field :idTransport%>
  	</div>
  	
  	<div class = "field">
  		<%= f.label :idDetail%>
  		<%= f.text_field :idDetail%>
  		
  		</div>
  
  <div class="actions">

    <%= f.submit %>
  </div>
<% end %>

Envios/app/views/envios/edit.html.erb
<h1>Editing Envio</h1>

<%= render 'form' %>

<%= link_to 'Show', @envio %> |
<%= link_to 'Back', envios_path %>

Envios/app/views/envios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Envios</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @envios.each do |envio| %>
      <tr>
        <td><%= link_to 'Show', envio %></td>
        <td><%= link_to 'Edit', edit_envio_path(envio) %></td>
        <td><%= link_to 'Destroy', envio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Envio', new_envio_path %>

Envios/app/views/envios/new.html.erb
<h1>New Envio</h1>

<%= render 'form' %>

<%= link_to 'Back', envios_path %>

Envios/app/views/envios/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_envio_path(@envio) %> |
<%= link_to 'Back', envios_path %>

Envios/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Envios</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>